In [ ]:
# import necessary packages
import pandas as pd
import numpy as np
import json

Mounted at /content/gdrive

In [ ]:
# read in data from Cell_Phones_&_Accessories.json
data = []
with open('Cell_Phones_and_Accessories.json', 'r') as file:
    for line in file:
        data.append(json.loads(line))

df = pd.DataFrame(data)

In [ ]:
# read in meta-data from meta_Cell_Phones_and_Accessories.json
data = []
with open('meta_Cell_Phones_and_Accessories.json', 'r') as file:
    for line in file:
        data.append(json.loads(line))

df_meta = pd.DataFrame(data)

In [ ]:
df_meta.head()

,category,tech1,description,fit,title,also_buy,tech2,brand,feature,rank,also_view,details,main_cat,similar_item,date,price,asin,imageURL,imageURLHighRes
0,"[Cell Phones & Accessories, Accessories, Scree...",,[],,Trollies Sing a Long Party VHS,[],,,[],"557,379 in Movies & TV (",[],{'ASIN: ': '6303195164'},Movies & TV,,,,6303195164,[],[]
1,"[Cell Phones & Accessories, Accessories, Car A...",,[],,La Pura VHS,[],,Maribel Guardia,[],"1,024,449 in Movies & TV (",[],{'ASIN: ': '630524412X'},Movies & TV,,,,630524412X,[],[]
2,"[Cell Phones & Accessories, Cases, Holsters & ...",,"[New items to give you a new good mood, welcom...",,Leopard Thanksgiving Easter PC Black Case for ...,[],,,[],"5,315,017 in Books (",[],"{'Publisher:': 'juduiou', 'ASIN:': '6310200240...",Books,,,,6310200240,[],[]
3,"[Cell Phones & Accessories, Cases, Holsters & ...",,"[A brand-new, unused, unopened, undamaged item...",,Puppies Faceplate Hard Case Protector for Net1...,[],,Live2Pedal,[Protect your phone with style through this At...,"[>#6,368,825 in Cell Phones & Accessories (See...",[],{},Cell Phones & Accessories,,,,6786501710,[],[]
4,"[Cell Phones & Accessories, Cases, Holsters & ...",,"[A brand-new, unused, unopened, undamaged item...",,White Wolf Faceplate Protector Hard Case for S...,[],,wirelessoutletusa,[Protect your phone with style through this At...,"[>#2,672,454 in Cell Phones & Accessories (See...",[],{},Cell Phones & Accessories,,,,6786501273,[],[]

In [ ]:
# filter for apple df_meta and extract the asin numbers (product IDs)
df_meta = df_meta[df_meta['brand'] == 'Apple']
df_meta = df_meta[['asin', 'brand']]
print(df_meta.shape)
df_meta.head()

In [ ]:
# merge df and df_meta to filter for only apple products (based on the product IDs)
df = pd.merge(df, df_meta, on='asin', how='inner')
print(df.shape)
df.head()

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,image,style,brand
0,5.0,True,"10 3, 2010",A9H9C0WF6JTG3,8199201460,Rubybird,All I can say is that it came in perfect condi...,just what I was looking for,1286064000,NaN,NaN,NaN,Samsung
1,5.0,True,"04 23, 2015",AK1M247BOU73P,8199201460,Susan H.,Thanks! This vendor was fast and item was as ...,Thanks! This vendor was fast and item was as ...,1429747200,NaN,NaN,NaN,Samsung
2,5.0,True,"11 24, 2014",A21AMFQK5SGWTC,8199201460,Adipocere,Works as expected.,Works as expected.,1416787200,NaN,NaN,NaN,Samsung
3,5.0,False,"10 18, 2014",A3NXF3DJ76YN27,8199201460,SPENCER,"Was a official Samsung charger,ordered 2 & ver...",Love Amazon,1413590400,NaN,NaN,NaN,Samsung
4,4.0,True,"05 23, 2014",A2XEIXD9SXFVTZ,8199201460,Mark,"I have a Samsung a777. This fits perfect, cha...",Works! Nice Build Quality,1400803200,NaN,NaN,NaN,Samsung

In [ ]:
# write (much smaller) df to csv file
df.to_csv('apple.csv', index=False)